window.ShaderStudy = window.ShaderStudy || {};
window.ShaderStudy.Theory = window.ShaderStudy.Theory || {};
window.ShaderStudy.Theory["ch2-l1"] = `
          <h2 id="2.0.1">2.0.1. What is a shader?</h2>
          <p>Xem xét một vài kiến thức trước đây, chúng ta sẽ đi sâu vào chủ đề về shaders trong Unity. Một <strong>shader</strong> là một chương trình nhỏ với phần đuôi mở rộng "<code>.shader</code>" (ví dụ: <code>color.shader</code>), có thể được sử dụng để tạo ra các hiệu ứng thú vị trong dự án của chúng ta. Bên trong nó, có chứa các phép tính toán học và danh sách các tập lệnh (commands) nền tảng, cho phép xử lý màu sắc (color processing) cho từng <strong>pixel</strong> nằm trong vùng diện tích bao phủ một đối tượng trên màn hình máy tính.</p>
          <p>Chương trình này cho phép chúng ta vẽ nên các thành phần (bằng cách sử dụng các hệ thống tọa độ - coordinate systems) dựa thuận theo các thuộc tính của một polygonal object. Các shaders được thực thi mạnh mẽ bởi <strong>GPU</strong> vì card đồ họa sở hữu một kiến trúc song song (parallel architecture) bao gồm hàng ngàn lõi nhân (cores) nhỏ gọn, hiệu năng cao, được thiết kế chuyên biệt để giải quyết các tác vụ đồng thời, trong khi CPU vốn chỉ được thiết kế thiên hướng về xử lý tuần tự (sequential serial processing).</p>
          <p>Lưu ý rằng Unity hỗ trợ ba loại files khác biệt liên quan đến shaders. Thứ nhất, chúng ta có các chương trình mang tệp định dạng "<code>.shader</code>" hoàn toàn có công năng biên dịch độc lập (compiling) xuyên suốt các loại <strong>render pipelines</strong> khác nhau.</p>
          <p>Thứ hai, chúng ta có các chương trình với tệp mở rộng "<code>.shadergraph</code>" mà chỉ có thể độc quyền biên dịch giới hạn hoặc trong <strong>Universal RP</strong> hoặc trong <strong>High Definition RP</strong>. Ngoài ra, chúng ta còn sở hữu dạng tệp mở rộng "<code>.hlsl</code>" cấp quyền cho chúng ta dễ dàng tạo ra những customized functions mang tính cá nhân hóa cao; dạng file này thường được lôi ra sử dụng triệt để khi chèn vào trong một node có tên là <strong>Custom Function</strong>, một tính năng tìm thấy bên trong Shader Graph.</p>
          <p>Cũng không thể không nhắc tới một loại chương trình khác có phần mở rộng "<code>.cginc</code>" mà chúng ta sẽ xem xét cụ thể sau. Tuy nhiên ngay lúc này, chúng ta sẽ tạm hạn chế bản thân thông qua việc ghi nhận tính liên kết tiếp theo đây: "<code>.cginc</code>" được liên kết trực tiếp với "<code>.shader</code>" <code>CGPROGRAM</code>, và "<code>.hlsl</code>" thì được gắn với "<code>.shadergraph</code>" <code>HLSLPROGRAM</code>.</p>
          <p>Hiểu rõ sự tương đồng này là vô cùng nền tảng, mấu chốt, bởi vì mỗi tệp file đuôi mở rộng đóng vai trò hoàn thành một function sai khác nhất định và được sử dụng hợp lý trong từng bối cảnh cụ thể.</p>

          <div class="lesson-fig">
            <div class="fig-placeholder">
              <span class="fig-placeholder-icon">🖼️</span>
              <span class="fig-placeholder-text">Yêu cầu ảnh: Fig. 2.0.1a</span>
              <span class="fig-placeholder-path">assets/ch2/fig_2_0_1a.png</span>
            </div>
            <figcaption>Hình 2.0.1a: Các biểu tượng icon tham khảo dành cho những file liên quan đến shaders trong Unity.</figcaption>
          </div>

          <p>Trong Unity, luôn có sẵn ít nhất bốn loại hệ cấu trúc được định nghĩa từ trước để nhào nặn nên shaders, trong đó chúng ta có thể tìm thấy sự kết hợp giữa <strong>vertex shader</strong> và <strong>fragment shader</strong>, kế đến là <strong>surface shader</strong> cho việc tính toán chiếu sáng tự động (automatic lighting calculation) và khép lại với <strong>compute shader</strong> hướng tới xử lý các khái niệm vĩ mô, nâng cao hơn nhiều.</p>
          <p>Mỗi một cấu trúc này đã được định sẵn các properties đi kèm hệ thống lệnh gọi hàm xuất sắc để làm mượt mà phần khởi biên dịch (compilation process); vì vậy dĩ nhiên việc định nghĩa các operations của riêng mình trở nên quá dễ dàng, do bản thân phần mềm đã chủ động chèn các cấu trúc này một cách rất tự động hóa.</p>

          <h2 id="2.0.2">2.0.2. Introduction to the programming language</h2>
          <p>Trước khi bắt đầu chìm lấp trong mớ kiến thức code, chúng ta buộc phải để tâm lưu ý rằng trong Unity tồn tại rạch ròi ba ngôn ngữ lập trình đồng hành chung với việc phát triển shader, đó chính là <strong>HLSL</strong> (High-Level Shader Language - do Microsoft phát triển), <strong>Cg</strong> (C for Graphics - của NVIDIA tạo ra) thứ ngôn ngữ đến nay mặc dù vẫn biên dịch được vào shader nhưng thực tế không còn được sử dụng trong các phên bản phần mềm gần đây nữa, và cuối cùng là <strong>ShaderLab</strong> (một loại declarative language - ngôn ngữ biểu đạt khai báo của Unity).</p>
          <p>Chúng ta sẽ bắt đầu chuyến phiêu lưu của mình xoay vòng với ngôn ngữ Cg và ShaderLab ngay trong môi trường Built-in RP và chậm rãi nhường không gian cho sự ra mắt của HLSL trong nền tảng Universal RP sau đó.</p>
          <p>Cg là một ngôn ngữ lập trình cấp cao (high-level programming language) siêu hạng thiết kế để biên dịch ngon ơ trên đa số nền tảng GPU. Được kiến tạo bởi đội ngũ NVIDIA dưới sự hợp tác cùng Microsoft, Cg ngang nhiên phô diễn một hệ cú pháp syntax tương đồng cực sâu sắc với HLSL.</p>
          <p>Lý do thật sự giải thích tại sao hệ thống shaders lại làm việc ăn ý với ngôn ngữ Cg là bởi vì nó có thể dung nạp biên dịch được cả hai thứ <strong>HLSL</strong> và <strong>GLSL</strong> (OpenGL Shading Language), qua đó đẩy nhanh và tối ưu quá trình tạo ra các materials ngốn tài nguyên dành cho video games.</p>
          <p>Một khi chúng ta tạo ra một shader, đoạn mã code của chúng ta sẽ được khoanh vùng biên dịch trong một giới hạn khu vực gọi nôm na là <code>CGPROGRAM</code>. Unity hiện nay đang làm việc vô cùng miệt mài nhằm không ngừng bơm cung cấp những bản hỗ trợ sâu hơn vì tính tương thích hoàn hảo giữa Cg và HLSL, do vậy chúng ta có thể cho rằng một ngày nào đó không lâu tới nhóm khối block code này nhất khoát sẽ triệt để bị thay thế bởi <code>HLSLPROGRAM</code> và <code>ENDHLSL</code>, điều này có cơ sở do chính bản thân HLSL đã chính thức trở thành ngôn ngữ quốc ngữ lập trình shader chính quy kể từ dòng các phiên bản phần mềm đương đại của Unity (thế hệ version 2019 trở đi).</p>
          <p>Tất thảy mọi shaders tồn tại trong Unity (loại trừ nhóm tính năng Shader Graph và Compute) bao trùm tất thảy đều phải được viết trong ngăn cách của một ngôn ngữ biểu đạt gọi là <strong>ShaderLab</strong>. Ngữ pháp syntax của loại ngôn ngữ này cho phép phơi bày lộ diện các thuộc tính (properties) của shader ra thẳng giao diện Unity inspector (bảng thuộc tính Unity). Đây là một điều rất lý thú vì chúng ta có thể điều khiển các tham số thông số trực tiếp của biến số và vectors theo thời gian thực real-time, uốn nắn shader gò theo đúng hướng kết quả kỳ vọng hoàn hảo.</p>
          <p>Tại vùng lập trình ShaderLab, chúng ta có thể định nghĩa bằng tay nhiều lớp properties và các khối commands, đơn cử ở đây chính là khối dự phòng an toàn <strong>Fallback</strong> block, tương thích liền mạch với các chủng loại render pipelines hiện hành đang có mặt trên thị trường.</p>
          <p>Fallback đích xác là một block căn bản nền tảng đối với các tựa game đa nền chuẩn multiplatform. Trọng trách của nó là cho phép trình biên dịch trỏ qua biên dịch một mã lệnh shader hoàn toàn khác rẽ nhánh ngay khoảnh khắc shader đang dùng sinh mã lỗi sinh error. Nếu cái shader bị phá hỏng trong công đoạn biên dịch (compilation process), Fallback sẽ quăng trả lại một thể shader thay thế vào khuôn hình, và thế là, phần mềm phần cứng đồ họa thỏa sức tiếp tục duy trì hoạt động làm việc nhịp nhàng qua ngày.</p>
          <p><strong>SubShader</strong> là danh xưng cho một khối lệnh block đỉnh cao khác chễm chệ trong ShaderLab, khối block này cấp quyền để chúng ta khai báo trớt lọt các khối commands (các câu lệnh) và liên tiếp sản sinh chuỗi passes. Khi được viết dưới ngôn ngữ Cg/HLSL, trọn vẹn cấu trúc bên trong một shader hoàn toàn có thể ôm gọn cưu mang nhiều SubShaders nội tại hoặc đa số chuỗi lượt pass chèn đè, thề tuy nhiên, trong trường hợp liên hệ Scriptable RP, thì một shader đành đóng khuôn hạn chế và cũng chỉ có thể chứa duy nhất một thẻ pass nhõn cho mỗi một SubShader mặt của nó thôi.</p>
          <h2 id="2.0.5">2.0.5. Unlit Shader</h2>
          <p>Không bị ảnh hưởng bởi ánh sáng, phù hợp cho thiết bị cấu hình thấp.</p>
`;
