window.ShaderStudy = window.ShaderStudy || {};
window.ShaderStudy.Theory = window.ShaderStudy.Theory || {};
window.ShaderStudy.Theory["ch2-l1"] = `
          <h2 id="2.0.1">2.0.1. What is a shader?</h2>
          <p>Xem xét một vài kiến thức trước đây, chúng ta sẽ đi sâu vào chủ đề về shaders trong Unity. Một <strong>shader</strong> là một chương trình nhỏ với phần đuôi mở rộng "<code>.shader</code>" (ví dụ: <code>color.shader</code>), có thể được sử dụng để tạo ra các hiệu ứng thú vị trong dự án của chúng ta. Bên trong nó, có chứa các phép tính toán học và danh sách các tập lệnh (commands) nền tảng, cho phép xử lý màu sắc (color processing) cho từng <strong>pixel</strong> nằm trong vùng diện tích bao phủ một đối tượng trên màn hình máy tính.</p>
          <p>Chương trình này cho phép chúng ta vẽ nên các thành phần (bằng cách sử dụng các hệ thống tọa độ - coordinate systems) dựa thuận theo các thuộc tính của một polygonal object. Các shaders được thực thi mạnh mẽ bởi <strong>GPU</strong> vì card đồ họa sở hữu một kiến trúc song song (parallel architecture) bao gồm hàng ngàn lõi nhân (cores) nhỏ gọn, hiệu năng cao, được thiết kế chuyên biệt để giải quyết các tác vụ đồng thời, trong khi CPU vốn chỉ được thiết kế thiên hướng về xử lý tuần tự (sequential serial processing).</p>
          <p>Lưu ý rằng Unity hỗ trợ ba loại files khác biệt liên quan đến shaders. Thứ nhất, chúng ta có các chương trình mang tệp định dạng "<code>.shader</code>" hoàn toàn có công năng biên dịch độc lập (compiling) xuyên suốt các loại <strong>render pipelines</strong> khác nhau.</p>
          <p>Thứ hai, chúng ta có các chương trình với tệp mở rộng "<code>.shadergraph</code>" mà chỉ có thể độc quyền biên dịch giới hạn hoặc trong <strong>Universal RP</strong> hoặc trong <strong>High Definition RP</strong>. Ngoài ra, chúng ta còn sở hữu dạng tệp mở rộng "<code>.hlsl</code>" cấp quyền cho chúng ta dễ dàng tạo ra những customized functions mang tính cá nhân hóa cao; dạng file này thường được lôi ra sử dụng triệt để khi chèn vào trong một node có tên là <strong>Custom Function</strong>, một tính năng tìm thấy bên trong Shader Graph.</p>
          <p>Cũng không thể không nhắc tới một loại chương trình khác có phần mở rộng "<code>.cginc</code>" mà chúng ta sẽ xem xét cụ thể sau. Tuy nhiên ngay lúc này, chúng ta sẽ tạm hạn chế bản thân thông qua việc ghi nhận tính liên kết tiếp theo đây: "<code>.cginc</code>" được liên kết trực tiếp với "<code>.shader</code>" <code>CGPROGRAM</code>, và "<code>.hlsl</code>" thì được gắn với "<code>.shadergraph</code>" <code>HLSLPROGRAM</code>.</p>
          <p>Hiểu rõ sự tương đồng này là vô cùng nền tảng, mấu chốt, bởi vì mỗi tệp file đuôi mở rộng đóng vai trò hoàn thành một function sai khác nhất định và được sử dụng hợp lý trong từng bối cảnh cụ thể.</p>

          <div class="lesson-fig">
            <div class="fig-placeholder">
              <span class="fig-placeholder-icon">🖼️</span>
              <span class="fig-placeholder-text">Yêu cầu ảnh: Fig. 2.0.1a</span>
              <span class="fig-placeholder-path">assets/ch2/fig_2_0_1a.png</span>
            </div>
            <figcaption>Hình 2.0.1a: Các biểu tượng icon tham khảo dành cho những file liên quan đến shaders trong Unity.</figcaption>
          </div>

          <p>Trong Unity, luôn có sẵn ít nhất bốn loại hệ cấu trúc được định nghĩa từ trước để nhào nặn nên shaders, trong đó chúng ta có thể tìm thấy sự kết hợp giữa <strong>vertex shader</strong> và <strong>fragment shader</strong>, kế đến là <strong>surface shader</strong> cho việc tính toán chiếu sáng tự động (automatic lighting calculation) và khép lại với <strong>compute shader</strong> hướng tới xử lý các khái niệm vĩ mô, nâng cao hơn nhiều.</p>
          <p>Mỗi một cấu trúc này đã được định sẵn các properties đi kèm hệ thống lệnh gọi hàm xuất sắc để làm mượt mà phần khởi biên dịch (compilation process); vì vậy dĩ nhiên việc định nghĩa các operations của riêng mình trở nên quá dễ dàng, do bản thân phần mềm đã chủ động chèn các cấu trúc này một cách rất tự động hóa.</p>

          <h2 id="2.0.2">2.0.2. Introduction to the programming language</h2>
          <p>Trước khi bắt đầu chìm lấp trong mớ kiến thức code, chúng ta buộc phải để tâm lưu ý rằng trong Unity tồn tại rạch ròi ba ngôn ngữ lập trình đồng hành chung với việc phát triển shader, đó chính là <strong>HLSL</strong> (High-Level Shader Language - do Microsoft phát triển), <strong>Cg</strong> (C for Graphics - của NVIDIA tạo ra) thứ ngôn ngữ đến nay mặc dù vẫn biên dịch được vào shader nhưng thực tế không còn được sử dụng trong các phên bản phần mềm gần đây nữa, và cuối cùng là <strong>ShaderLab</strong> (một loại declarative language - ngôn ngữ biểu đạt khai báo của Unity).</p>
          <p>Chúng ta sẽ bắt đầu chuyến phiêu lưu của mình xoay vòng với ngôn ngữ Cg và ShaderLab ngay trong môi trường Built-in RP và chậm rãi nhường không gian cho sự ra mắt của HLSL trong nền tảng Universal RP sau đó.</p>
          <p>Cg là một ngôn ngữ lập trình cấp cao (high-level programming language) siêu hạng thiết kế để biên dịch ngon ơ trên đa số nền tảng GPU. Được kiến tạo bởi đội ngũ NVIDIA dưới sự hợp tác cùng Microsoft, Cg ngang nhiên phô diễn một hệ cú pháp syntax tương đồng cực sâu sắc với HLSL.</p>
          <p>Lý do thật sự giải thích tại sao hệ thống shaders lại làm việc ăn ý với ngôn ngữ Cg là bởi vì nó có thể dung nạp biên dịch được cả hai thứ <strong>HLSL</strong> và <strong>GLSL</strong> (OpenGL Shading Language), qua đó đẩy nhanh và tối ưu quá trình tạo ra các materials ngốn tài nguyên dành cho video games.</p>
          <p>Một khi chúng ta tạo ra một shader, đoạn mã code của chúng ta sẽ được khoanh vùng biên dịch trong một giới hạn khu vực gọi nôm na là <code>CGPROGRAM</code>. Unity hiện nay đang làm việc vô cùng miệt mài nhằm không ngừng bơm cung cấp những bản hỗ trợ sâu hơn vì tính tương thích hoàn hảo giữa Cg và HLSL, do vậy chúng ta có thể cho rằng một ngày nào đó không lâu tới nhóm khối block code này nhất khoát sẽ triệt để bị thay thế bởi <code>HLSLPROGRAM</code> và <code>ENDHLSL</code>, điều này có cơ sở do chính bản thân HLSL đã chính thức trở thành ngôn ngữ quốc ngữ lập trình shader chính quy kể từ dòng các phiên bản phần mềm đương đại của Unity (thế hệ version 2019 trở đi).</p>
          <p>Tất thảy mọi shaders tồn tại trong Unity (loại trừ nhóm tính năng Shader Graph và Compute) bao trùm tất thảy đều phải được viết trong ngăn cách của một ngôn ngữ biểu đạt gọi là <strong>ShaderLab</strong>. Ngữ pháp syntax của loại ngôn ngữ này cho phép phơi bày lộ diện các thuộc tính (properties) của shader ra thẳng giao diện Unity inspector (bảng thuộc tính Unity). Đây là một điều rất lý thú vì chúng ta có thể điều khiển các tham số thông số trực tiếp của biến số và vectors theo thời gian thực real-time, uốn nắn shader gò theo đúng hướng kết quả kỳ vọng hoàn hảo.</p>
          <p>Tại vùng lập trình ShaderLab, chúng ta có thể định nghĩa bằng tay nhiều lớp properties và các khối commands, đơn cử ở đây chính là khối dự phòng an toàn <strong>Fallback</strong> block, tương thích liền mạch với các chủng loại render pipelines hiện hành đang có mặt trên thị trường.</p>
          <p>Fallback đích xác là một block căn bản nền tảng đối với các tựa game đa nền chuẩn multiplatform. Trọng trách của nó là cho phép trình biên dịch trỏ qua biên dịch một mã lệnh shader hoàn toàn khác rẽ nhánh ngay khoảnh khắc shader đang dùng sinh mã lỗi sinh error. Nếu cái shader bị phá hỏng trong công đoạn biên dịch (compilation process), Fallback sẽ quăng trả lại một thể shader thay thế vào khuôn hình, và thế là, phần mềm phần cứng đồ họa thỏa sức tiếp tục duy trì hoạt động làm việc nhịp nhàng qua ngày.</p>
          <p><strong>SubShader</strong> là danh xưng cho một khối lệnh block đỉnh cao khác chễm chệ trong ShaderLab, khối block này cấp quyền để chúng ta khai báo trớt lọt các khối commands (các câu lệnh) và liên tiếp sản sinh chuỗi passes. Khi được viết dưới ngôn ngữ Cg/HLSL, trọn vẹn cấu trúc bên trong một shader hoàn toàn có thể ôm gọn cưu mang nhiều SubShaders nội tại hoặc đa số chuỗi lượt pass chèn đè, thề tuy nhiên, trong trường hợp liên hệ Scriptable RP, thì một shader đành đóng khuôn hạn chế và cũng chỉ có thể chứa duy nhất một thẻ pass nhõn cho mỗi một SubShader mặt của nó thôi.</p>
          <h2 id="2.0.3">2.0.3. Shader types</h2>
          <p>Để bắt đầu tạo ra một shader, trước tiên chúng ta phải khởi tạo một project mới trong Unity. Nếu bạn đang sử dụng Unity Hub, nhà phát triển khuyến nghị nên tạo project ở các phiên bản phần mềm gần đây nhất (ví dụ: 2019, 2020 hoặc 2021).</p>
          <p>Chúng ta sẽ cần một <strong>3D template</strong> tích hợp sẵn <strong>Built-in RP</strong> để tạo điều kiện thuận lợi nhất nhằm thấu hiểu ngôn ngữ lập trình đồ họa. Khi thư mục project đã được thiết lập xong, chúng ta nhấp chuột phải vào cửa sổ <strong>Project Window</strong> (phím tắt <code>Ctrl + 5</code> hoặc <code>Cmd + 5</code>), trỏ đến thẻ <strong>Create</strong> và chọn tùy chọn <strong>Shader</strong>.</p>
          
          <div class="lesson-fig">
            <div class="fig-placeholder">
              <span class="fig-placeholder-icon">🖼️</span>
              <span class="fig-placeholder-text">Yêu cầu ảnh: Fig. 2.0.3a</span>
              <span class="fig-placeholder-path">assets/ch2/fig_2_0_3a.png</span>
            </div>
            <figcaption>Hình 2.0.3a: Chúng ta có thể đạt được cùng một kết quả cài đặt nếu đi theo đường dẫn Assets / Create / Shader trên hệ thanh công cụ.</figcaption>
          </div>

          <p>Như chúng ta có thể thấy, có nhiều hơn một loại shader ở đây, trong số đó trải đều những cái tên quen thuộc:</p>
          <ul>
            <li>Standard Surface Shader.</li>
            <li>Unlit Shader.</li>
            <li>Image Effect Shader.</li>
            <li>Compute Shader.</li>
            <li>Ray Tracing Shader.</li>
          </ul>
          <p>Danh sách đề xuất các đuôi shaders này rất có thể sẽ có sự dao động không ngừng tùy thuộc vào thế hệ phiên bản Unity được sử dụng để khởi tạo project lúc đó. Một biến số tham chiếu khác có thể tác động đến số lượng các shaders xuất đầu lộ diện trong danh sách này chính là <strong>Shader Graph</strong>. Nếu project được kiến tạo bằng môi trường <strong>Universal RP</strong> hay <strong>High Definition RP</strong>, nó có thể đã được tự động bơm sẵn gói package Shader Graph từ trong trứng nước, điều mà chắc chắn sẽ làm tăng số lượng danh mục type shaders có thể tạo ra qua menu.</p>
          <p>Tạm thời trong thời gian tới, chúng ta sẽ chưa vội vã đi sâu vào chi tiết bóc tách về chủ đề này; do chúng ta phải hiểu thấu đáo vài khái niệm cốt lõi trước khi lao vào với những kiến thức nâng cao đó, bởi vậy chúng ta sẽ chỉ thu hẹp bản thân trong việc cày cuốc với những đuôi shaders tự động đi kèm mặc định (come by default) trong nền tảng nhóm <strong>Built-in RP</strong>.</p>
          <p>Tuy vậy, trước khi nhào nặn ra chiếc shader đầu tiên của mình, chúng ta vẫn sẽ dành thời gian thực hiện một bài đánh giá thu nhỏ gọn gàng về các chủng loại shader khác nhau đang hiện hữu trong lòng phần mềm engine này.</p>

          <h2 id="2.0.4">2.0.4. Standard surface shader</h2>
          <p>Khuôn mẫu shader này được định dạng bởi khả năng tối ưu hóa sâu trong khâu viết từ vựng mã code chuyên biệt để nó kết nối tương tác cực chặt chẽ với một mô hình ánh sáng cơ bản (basic lighting model) và rào cản là nó chỉ nhận lệnh làm việc túc trực trong môi trường <strong>Built-in RP</strong>. Nếu chúng ta nhắm tới mục đích đẽo ra một mảng shader có khả năng năng tương tác phơi sáng (interacts with light), chúng ta có hai định hướng lựa chọn như sau:</p>
          <ol>
            <li>Rinh một chiếc Unlit Shader thô sơ vào và tự tay thủ công vỗ thêm một mớ ti tỉ các hàm toán học (mathematical functions) phức tạp lằng nhằng nhằm mục đích mở khóa quyền kết xuất quang học (lighting rendering) đè lên bề mặt đối tượng vật liệu.</li>
            <li>Hoặc cách mạng hơn là dùng luôn một mảnh <strong>Standard Surface Shader</strong> ăn sẵn, thứ vốn dĩ đã được trang bị tới tận răng một mô hình chiếu sáng cơ sở mà trong đa phần các trường hợp nó đã thầm bao hàm đầy đủ dữ liệu móng như <strong>albedo</strong> (màu bản thể), <strong>specular</strong> (phản xạ gương sắc nét), và <strong>diffuse</strong> (phản xạ khuếch tán bề mặt thô).</li>
          </ol>

          <h2 id="2.0.5">2.0.5. Unlit shader</h2>
          <p>Chữ "Lit" có nghĩa là ám chỉ một hệ mặt đối tượng nguyên liệu bị thay đổi bởi tính chất chiếu sáng (illumination), và như thế nhóm "Unlit" hoàn toàn đại diện cho một ý nghĩa trái ngược vô ưu. Loại vật thể mang cấu trúc Shader Unlit tự liên hệ bản thân đến với những mô hình màu sắc thuần túy (primary color model) và mặc nhiên nó sẽ được ưu tiên bốc làm cấu trúc khung sườn nền tảng mà chúng ta thường hay sử dụng làm đệm bàn đạp để dấy tạo các hiệu ứng đồ họa cá nhân sau này. Loại thiết lập tinh gọn này, thực ra rất lý tưởng cho những cấp độ phần cứng thấp bét (low-end hardware) vì vốn dĩ không tích hợp tính năng tự động tối ưu mã ngầm; chính vì vậy, chúng ta có thể vô tình mục sở thị dòm thấu toàn bộ cấu trúc xương sống định dạng của file và tự do sửa phạt uốn xoắn nó tùy sức theo nhu cầu tinh chỉnh. Tính năng tuyệt nhất của dòng thác này là nó nịnh bợ trung thành trên cả 2 trạm thiết bị <strong>Built-in</strong> lẫn <strong>Scriptable RP</strong>.</p>

          <h2 id="2.0.6">2.0.6. Image effect shader</h2>
          <p>Nếu xét về mặt hình hài kết cấu thì kiểu dáng tổ chức của nó giống đến kinh ngạc với một đuôi khuôn Unlit Shader. Image effects (Hiệu ứng hình mảng) được đem ra công chiếu triển khai chủ yếu đóng đinh trong những khâu độ họa hậu kỳ (post-processing effects) nếu project chạy chuẩn Built-in RP, ngoài lề chúng còn giơ yêu sách bắt buộc phải ghim gọi lệnh function "<code>OnRenderImage</code>" (trong nền móng mã <strong>C#</strong>) kèm cặp đính kèm.</p>

          <h2 id="2.0.7">2.0.7. Compute shader</h2>
          <p>Khuôn mẫu lập trình khủng này được đánh giá cao bởi khả năng chễm chệ chạy trơn tru nhịp nhàng trên thẳng nền tảng card màn hình đồ họa (graphics card), nằm hoàn toàn ngoài luồng lề chuỗi render pipeline truyền thống (normal render pipeline), và điều này vô tình dễ hiểu làm cho hệ kết cấu xương sườn gốc của nó khác biệt như ngày với đêm khi lấy ra soi xét so với hàng loạt nhóm shaders đã vinh danh phía trên bục.</p>
          <p>Thật sự khác biệt rất lớn so với nhóm shader phổ thông (common shader), chiếc đuôi định dạng mở rộng mà Compute Shader mang theo người có cái tên là "<code>.compute</code>" và ngỡ ngàng hơn đi kèm cùng việc đó là loại ngôn ngữ lập trình được sử dụng để nói chuyện với bộ phận này lại là loại <strong>HLSL</strong> chuẩn. Compute Shaders mang danh nghĩa là thứ vũ khí được sử dụng đặc cách trong một số phân cảnh yêu cầu đặc thù cốt để đẩy tua (speed up) tốc độ tính toán phần cứng cho một khối lượng dữ liệu khổng lồ của trò chơi.</p>
          <p>Phân chương thứ 3 của cuốn bí kíp dắt lưng này sẽ ngồi review lại chi tiết cặn kẽ mẫu lập trình đầy uy lực trên.</p>

          <h2 id="2.0.8">2.0.8. Ray tracing shader</h2>
          <p><strong>Ray Tracing Shader</strong> là một phân loài chương trình mang đậm tính chất thử nghiệm vỹ mô (experimental program) với chiếc đuôi mở rộng mang tên "<code>.raytrace</code>". Điểm mấu chốt là tự nó ban cho GPU tính năng thực thi phán đoán truyền dò tia đổ bóng vật lý (Ray Tracing processing). Tuy nhiên, quyền năng kinh hoàng này chỉ hoạt động duy nhất ở phân vùng dự án <strong>High Definition RP</strong> (HDRP) cũng như còn phải đèo bồng khá nhiều rào cản kỹ thuật giới hạn ở móng nền tảng. Nếu ước vọng là làm việc cọ xát với nền công nghệ quái vật DXR (DirectX Ray Tracing) khét tiếng, chúng ta bị ép bắt buộc trang bị vũ trang tối thiểu một con quái thú xử lý card đồ họa <strong>GTX 1080</strong> hoặc các loại dàn máy siêu hạng tương đương ăn chơi chức năng bật phần cứng RTX support, chạy cài đặt tối thiểu phiên bản <strong>Windows 10 version 1809+</strong> cũng như cõng bộ engine lõi Unity 2019.3b1 đổ lên đời mới nhất.</p>
          <p>Chúng ta có thể cậy nhờ vào thứ loại chương trình hạng xịn này để thay thế thế chỗ phế truất luôn dòng "<code>.compute</code>" type shader hòng tính toán nhai gọn các khối thuật toán xử lý dữ liệu truyền hình dò tia phóng (ray-casting), ví dụ điển hình nhức nách như: chiếu sáng toàn cục (global illumination), độ bóng mượt (reflections), hiện tượng khúc xạ ánh sáng (refraction) hoặc nảy tính tụ quang chùm tia nắng (caustic).</p>
`;
